name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[default]" >> ~/.aws/config
          echo "region = ap-northeast-2" >> ~/.aws/config

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: private
          skip-logout: false

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URL }}:<IMAGE_TAG> .
          docker push ${{ secrets.ECR_REPOSITORY_URL }}:<IMAGE_TAG>

      - name: Create or update ECS service
        run: |
          aws ecs create-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service-name ${{ secrets.ECS_SERVICE_NAME }} --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --desired-count 1
